- platform: rgb
  name: ${devicename}_rgb
  id: ${devicename}_rgb
  red: output_red
  green: output_green
  blue: output_blue
  default_transition_length: 3s
  restore_mode: RESTORE_DEFAULT_OFF
  effects: !include effects.yaml
- platform: cwww
  name: ${devicename}_cwww
  id: ${devicename}_cwww
  warm_white: output_warm_white
  cold_white: output_cold_white
  cold_white_color_temperature: 6200 K
  warm_white_color_temperature: 2800 K
  default_transition_length: 3s
  restore_mode: RESTORE_DEFAULT_OFF
