  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO12
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    frequency: ${frequency_rgb}
