  - platform: rgb
    name: ${friendly_name} (RGB)
    id: ${devicename}_rgb
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 3s
    restore_mode: RESTORE_DEFAULT_OFF
    effects: !include effects.yaml
  - platform: monochromatic
    name: ${friendly_name} (W)
    id: ${devicename}_w
    output: output_white
    default_transition_length: 3s
    restore_mode: RESTORE_DEFAULT_OFF
