- platform: esp8266_pwm
  id: output_red
  pin: GPIO4
  frequency: $frequency_rgb
- platform: esp8266_pwm
  id: output_green
  pin: GPIO12
  frequency: $frequency_rgb
- platform: esp8266_pwm
  id: output_blue
  pin: GPIO14
  frequency: $frequency_rgb
- platform: esp8266_pwm
  id: output_warm_white
  pin: GPIO13
  frequency: $frequency_ww
  max_power: 0%
- platform: esp8266_pwm
  id: output_cold_white
  pin: GPIO5
  max_power: 0%
  frequency: $frequency_cw
