#- platform: version
#  name: "${friendly_name} ${room}  ESPHome Version"
#  icon: 'mdi:car-esp'
#  on_value:
#    then:
#      - lambda: |-
#          ESP_LOGD("main", "The current version is %s", x.c_str());
- platform: wifi_info
  ip_address:
    name: ${friendly_name} (${room}) IP Address
    icon: mdi:wifi
#  ssid:
#    name: ${friendly_name} (${room}) SSID
#    icon: mdi:wifi
#  bssid:
#    name: ${friendly_name} (${room}) BSSID
#    icon: mdi:wifi
