- platform: version
  name: "${friendly_name} ESPHome Version"
  icon: 'mdi:car-esp'
  on_value:
    then:
      - lambda: |-
          ESP_LOGD("main", "The current version is %s", x.c_str());
- platform: wifi_info
  ip_address:
    name: ${friendly_name} IP Address
    icon: mdi:wifi
  ssid:
    name: ${friendly_name} SSID
    icon: mdi:wifi
  bssid:
    name: ${friendly_name} BSSID
    icon: mdi:wifi
