  css_url: https://hass.internal.phixion.org:8123/local/_static/webserver-v1.min.css
  js_url: https://hass.internal.phixion.org:8123/local/_static/webserver-v1.min.js
  auth:
    username: !secret esphome_ota_usr
    password: !secret esphome_ota_pwd