#██████╗ ██╗███╗   ██╗ █████╗ ██████╗ ██╗   ██╗    ███████╗███████╗███╗   ██╗███████╗ ██████╗ ██████╗ 
#██╔══██╗██║████╗  ██║██╔══██╗██╔══██╗╚██╗ ██╔╝    ██╔════╝██╔════╝████╗  ██║██╔════╝██╔═══██╗██╔══██╗
#██████╔╝██║██╔██╗ ██║███████║██████╔╝ ╚████╔╝     ███████╗█████╗  ██╔██╗ ██║███████╗██║   ██║██████╔╝
#██╔══██╗██║██║╚██╗██║██╔══██║██╔══██╗  ╚██╔╝      ╚════██║██╔══╝  ██║╚██╗██║╚════██║██║   ██║██╔══██╗
#██████╔╝██║██║ ╚████║██║  ██║██║  ██║   ██║       ███████║███████╗██║ ╚████║███████║╚██████╔╝██║  ██║
#╚═════╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝       ╚══════╝╚══════╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝
#                                                                                                     
binary_sensor:
  - platform: workday
    name: Werktag
    country: DE
    province: BY
    excludes: [sat, sun, holiday]
    add_holidays:
      - 2019-12-24
  - platform: workday
    name: Werktag Morgen
    country: DE
    province: BY
    excludes: [sat, sun, holiday]
    add_holidays:
      - 2019-12-24
    days_offset: 1
  - platform: workday
    country: DE
    province: BY
    name: Feiertag Morgen
    workdays: [holiday]
    days_offset: 1
    excludes: []
  - platform: workday
    country: DE
    province: BY
    name: Feiertag in einer Woche
    workdays: [holiday]
    days_offset: 7
    excludes: []
  - platform: bayesian
    prior: 0.5
    name: "Martin's Presence"
    probability_threshold: 0.9
    observations:
      - entity_id: "device_tracker.pixel_gps"
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: "state"
        to_state: "home"
      - entity_id: "device_tracker.pixel_wifi"
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: "state"
        to_state: "home"
  - platform: template
    sensors:
      macbook_battery_level_low:
        value_template: "{{ (states.sensor.macbook_air_battery_level.state | float) < 25 }}"
        friendly_name: "MacBook battery is low"
      nexus_battery_level_low:
        value_template: "{{ (states.sensor.google_nexus_battery_level.state | float) < 25 }}"
        friendly_name: "Nexus battery is low"
      pixel_battery_level_low:
        value_template: "{{ (states.sensor.google_pixel_battery_level.state | float) < 25 }}"
        friendly_name: "Pixel battery is low"
      dark_outside:
        value_template: "{{ is_state('sun.sun', 'below_horizon') }}"
        friendly_name: "Dark Outside"
