#██████╗ ██╗███████╗ ██████╗ ██████╗  ██████╗ ███████╗
#██╔══██╗██║██╔════╝██╔════╝██╔═══██╗██╔════╝ ██╔════╝
#██║  ██║██║███████╗██║     ██║   ██║██║  ███╗███████╗
#██║  ██║██║╚════██║██║     ██║   ██║██║   ██║╚════██║
#██████╔╝██║███████║╚██████╗╚██████╔╝╚██████╔╝███████║
#╚═════╝ ╚═╝╚══════╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚══════╝
#
sensor:
  - platform: discogs
    token: !secret discogs_token # pragma: allowlist secret
    name: Plattensammlung
    monitored_conditions:
      - wantlist
      - random_record
      - collection
