recorder:
  purge_interval: 1
  purge_keep_days: 30
  db_url: !secret dburl
  exclude:
    entities:
      - sensor.reddit_gamedeals
      - sensor.tram
      - sensor.bus
      - sensor.u_bahn
      - sensor.bad_wifi_signal
      - sensor.flur_wifi_signal
      - sensor.kueche_wifi_signal
      - sensor.schalter_lavalampe_wifi_signal
      - sensor.schalter_whz_wifi_signal
      - sensor.schalter_bad_wifi_signal
      - sensor.schalter_kueche_wifi_signal
      - sensor.schalter_flur_whz_wifi_signal
      - sensor.sonoff_pow_r2_tv_wifi_signal
      - sensor.sonoff_th16_whz_wifi_signal
      - sensor.sonoff_pow_r2_whz_wifi_signal
      - sensor.bulbspotwhztv_wifi_signal
      - sensor.bulbspotdesk_wifi_signal
      - sensor.wohnzimmer_stehlampe_wifi_signal
      - sensor.led_strip_wohnzimmer_1_wifi_signal
      - sensor.led_strip_wohnzimmer_2_wifi_signal
      - sensor.led_strip_wohnzimmer_3_wifi_signal
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.last_boot
      - sensor.btc_exchange_rate
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_humidity
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.circadian_values
      - sensor.climate_flur_battery
      - sensor.climate_roomstat_battery
      - sensor.climate_wohnzimmer_battery
      - sensor.climate_bad_battery
      - sensor.climate_flur_battery_voltage
      - sensor.climate_roomstat_battery_voltage
      - sensor.climate_wohnzimmer_battery_voltage
      - sensor.climate_bad_battery_voltage
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
      - automation
      - light
logbook:
  exclude:
    entities:
      - automation.update_morning_commute_sensor
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
history:
  exclude:
    entities:
      - automation.update_morning_commute_sensor
      - sensor.last_boot
      - sensor.date
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.ha_uptime
      - sensor.time
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing

logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.google_assistant.http: debug
