recorder:
  purge_keep_days: 5
  purge_interval: 1
  db_url: !secret dburl
  exclude:
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
      - light
      - automation
      - group
      - script
      - switch
      - zone
logbook:
  exclude:
    entities:
      - automation.update_morning_commute_sensor
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
history:
  exclude:
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
logger:
  default: info
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.google_assistant.http: debug
