language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y libudev-dev ffmpeg python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_upnp.yaml upnp.yaml
  - mv travis_zones.yaml zones.yaml
  - mv travis_panels.yaml panels.yaml
  - mkdir ./tmp
  - sed 's/\/config\/tmp/\/home\/travis\/build\/phixion\/Home\-AssistantConfig\/tmp/g' configuration.yaml > configuration_new.yaml
  - mv configuration_new.yaml configuration.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
