#████████╗██████╗  █████╗ ██╗   ██╗██╗███████╗     ██████╗██╗
#╚══██╔══╝██╔══██╗██╔══██╗██║   ██║██║██╔════╝    ██╔════╝██║
#   ██║   ██████╔╝███████║██║   ██║██║███████╗    ██║     ██║
#   ██║   ██╔══██╗██╔══██║╚██╗ ██╔╝██║╚════██║    ██║     ██║
#   ██║   ██║  ██║██║  ██║ ╚████╔╝ ██║███████║    ╚██████╗██║
#   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝  ╚═╝╚══════╝     ╚═════╝╚═╝
#
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -o Dpkg::Options::=--force-confnew libudev-dev ffmpeg python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
  - rename travis_ '' $(pwd)/travis/*.{yaml,json}
  - ln -s $(pwd)/travis/*.{yaml,json} .
  - sed -i "s@/config/tmp@$(pwd)/tmp@" configuration.yaml
  - mkdir $(pwd)/tmp
  - echo "# Netscape HTTP Cookie File\n0 0\n0 0\n0 0" > $(pwd)/.google_maps_location_sharing.cookies.joedoe_gmail_com
  - HA_VERSION=$(<.HA_VERSION)
install:
  - pip3 install homeassistant==${HA_VERSION}
script:
  - hass -c . --script check_config
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
