- alias: Vacation Mode
  trigger:
    platform: state
    entity_id: person.martin
    from: "home"
    to: "not_home"
    for:
      hours: 12
      minutes: 0
      seconds: 0
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: Vacation Mode
    - service: notify.pushover
      data:
        message: Vacation Mode turned ON
        title: 🌴 Vacation Mode turned ON
  id: a4476090f8f94f369735125d6506079f
- alias: Update
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    to: "on"
  action:
    - service: notify.pushover
      data:
        message: Update available
        title: Update available
  id: 18b95179215b42b78ee8a1f1cbdf7c1b
- alias: Turn off all lights/heating
  trigger:
    platform: state
    entity_id: person.martin
    from: "home"
    to: "not_home"
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
    - service: switch.turn_on
      entity_id: switch.wiser_away_mode
    - service: light.turn_off
      entity_id:
        - light.schalter_bad_light
        - light.schalter_flur_whz_light
        - light.schalter_whz_light
    - service: light.turn_off
      entity_id:
        - light.mood_lights
    - service: media_player.turn_off
      entity_id:
        - media_player.android_tv
        - media_player.shield
    - service: notify.pushover
      data_template:
        message: Temperatur ist {{states('sensor.climate_wohnung_temp')}}
        title: 🚫 Light's and Heating turned OFF
  id: a863cca2442c4de1a9125b19a0dba85f
- alias: Turn on all lights/heating
  trigger:
    platform: state
    entity_id: person.martin
    to: home
  action:
    - service: light.turn_on
      entity_id: light.schalter_flur_whz_light
    - service: switch.turn_off
      entity_id: switch.wiser_away_mode
    - service: climate.turn_on
      data:
        entity_id: climate.alle_thermostate
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.wiser_wohnzimmer
        hvac_mode: auto
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.wiser_bad
        hvac_mode: auto
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.wiser_flur
        hvac_mode: auto
    - service: notify.pushover
      data_template:
        title: 🚶 Martin got home!
        message: Temperatur ist {{states('sensor.climate_wohnung_temp')}}
    - service: notify.pushover
      data_template:
        message: Temperatur ist {{states('sensor.climate_wohnung_temp')}}
        title: ✅ Light's and Heating turned ON
    - service: media_player.turn_on
      entity_id: media_player.google_home
    - delay: 00:00:02
    - service: notify.google_assistant
      entity_id: media_player.google_home
      data:
        message: Hallo Martin
  id: df47ca4915274cf494fc429ae46aa3b1
- alias: Leave Home notification
  trigger:
    platform: state
    entity_id: person.martin
    from: "home"
    to: "not_home"
  #  condition:
  #    condition: time
  #    after: "20:00"
  action:
    service: notify.pushover
    data_template:
      title: 🚶 Martin left the flat
      message: "Event triggered: {{ trigger.entity_id }} changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
  id: aebd69cf232b488ca078745e1c1bdf4f
- alias: Badezimmer besetzt
  trigger:
    platform: state
    entity_id: switch.schalter_bad_relay
    to: "on"
  action:
    - service: notify.android
      data_template:
        title: 🚽 Badezimmer ist besetzt
        message: " "
  id: 2778047bc3fa4a6e9047ab0246961bd6
- alias: Badezimmer frei
  trigger:
    platform: state
    entity_id: switch.schalter_bad_relay
    to: "off"
  action:
    - service: notify.android
      data_template:
        title: 🚽 Badezimmer ist frei
        message: " "
  id: 2459b936fc0442459411361ba69453af
- id: update_morning_commute_sensor
  alias: Update morning commute sensor
  trigger:
    - platform: time_pattern
      minutes: /2
  condition:
    - condition: time
      after: 07:00:00
      before: "11:00:00"
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.morning_commute_trains
    - service: homeassistant.update_entity
      entity_id: sensor.morning_commute_bike
- id: weather_alert
  alias: Wetter Alarm
  trigger:
    - platform: state
      entity_id: sensor.alert
  condition:
    - condition: template
      value_template: "{{trigger.from_state.state != trigger.to_state.state}}"
  action:
    - service: script.all_notify
      data_template:
        title: Wetter Alarm
        message:
          "{%- if not is_state('sensor.alert', '0') -%}\n  {%- for s  in ['today',\
          \ 'tomorrow'] -%}\n    {%- set v = state_attr('sensor.w_alert', s) -%}\n \
          \   {%- if v -%}\n      {% for d  in v -%}\n        {{s}} - {{d['code']}}\
          \ {{d['event']}} {{d['end']}}\n      {% endfor -%}\n    {%- endif -%}\n  {%\
          \ endfor -%}\n{% else %}\n  alert expired\n{% endif %}"
- alias: Coinbase Wallet
  trigger:
    - platform: state
      entity_id: sensor.coinbase_eur_wallet
  condition:
    - condition: template
      value_template: "{{trigger.from_state.state != trigger.to_state.state}}"
  action:
    - service: notify.pushover
      data_template:
        title: ₿ Coinbase Wallet Value changed
        message: "Event triggered: {{ trigger.entity_id }} changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
- alias: Xur
  trigger:
    - platform: state
      entity_id: sensor.wtfisxur
  condition:
    - condition: template
      value_template: "{{trigger.from_state.state != trigger.to_state.state}}"
  action:
    - service: notify.pushover
      data_template:
        title: Xur changed location
        message: "Find him at: {{states('sensor.wtfisxur')}}"
