
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
upnp: !include upnp.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
panel_iframe: !include panels.yaml
sensor: !include sensors.yaml
discovery:
  ignore:
    - sabnzbd
sabnzbd:
  api_key: !secret sabnzbd_pwd
  host: !secret sabnzbhost
  name: !secret sabnzbd_usr
  port: 8243
  ssl: true
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size
logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.google_assistant.http: debug
ifttt:
  key: !secret iftttapi_pwd
wiser:
  host: !secret wiser_host
  password: !secret wiserapi_pwd
  scan_interval: 300
  boost_temp: 4
  boost_time: 1800
  minimum: 7

unifi:
  controllers:
    - host: !secret unifigw_host
      site: !secret unifigw_site
      ssid_filter:
        - !secret ssid_1
        - !secret ssid_2
      dont_track_devices: true
      dont_track_wired_clients: true
weather:
  - platform: darksky
    api_key: !secret weatherdarkskyapi_pwd
tts:
  - platform: google_translate
    cache: true
    cache_dir: /config/tts
  - platform: google_cloud
    key_file: !secret google_service_accout_json
    #    language: "de-DE"
    #    gender: "female"
    voice: "de-DE-Standard-A"
    cache: true
    cache_dir: /config/tts
  #    base_url: !secret base_url
  - platform: watson_tts
    watson_apikey: !secret ibm_cloud
    watson_url: !secret ibm_watson_url
    voice: "de-DE_BirgitV3Voice"
media_player:
  - platform: androidtv
    host: !secret host_androidtv
    name: Android TV
    device_class: androidtv
    adb_server_ip: localhost
    adb_server_port: 5037
    apps:
      com.google.android.youtube.tv: "Youtube"
      org.xbmc.kodi: "Kodi"
      com.netflix.ninja: "Netflix"
      com.google.android.tvlauncher: "Homescreen"
      com.plexapp.android: "Plex"
      com.liskovsoft.videomanager: "Youtube TV"
  - platform: spotify
    client_id: !secret spotifyapi_id
    client_secret: !secret spotifyapi_secret
#    aliases:
#        abc123def456: 'Living Room'
#        9183abas000: 'Bed Room'
http:
  base_url: !secret base_url
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem
vultr:
  api_key: !secret vultrapi_pwd
homeassistant:
  packages: !include integrations/common.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks: !include trustednetworks.yaml
      allow_bypass_login: true
  customize: !include customizations.yaml
  auth_mfa_modules:
    - type: totp
      name: Authy
    - type: notify
      message: "Hey, to get into my clubhouse, you need to say {}"
  name: Home
  time_zone: Europe/Berlin
  unit_system: metric
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_ela

light:
  - platform: group
    name: All Bulbs
    entities:
      - light.bulbflur
      - light.bulbkueche
      - light.bulbwhzlamp
      - light.bulbbad
      - light.schalter_bad_light
      - light.schalter_flur_whz_light
      - light.schalter_whz_light
  - platform: group
    name: All Spotlights
    entities:
      - light.bulbspotwhzdesk
      - light.bulbspotwhztv
  - platform: group
    name: All Lights
    entities:
      - light.all_bulbs
      - light.all_spotlights
  - platform: group
    name: Mood Lights
    entities:
      - light.bulbspotwhzdesk
      - light.bulbspotwhztv
      - light.bulbwhzlamp
      - light.ledstripwhz
# magichome led strip (destroyed by hias)
#  - platform: flux_led
#    automatic_add: true
#    scan_interval: 30
#    devices:
#      10.10.10.135:
#        name: rgbwstrip
#        mode: "rgb"
climate:
  - platform: climate_group
    name: "Alle Thermostate"
    entities:
      - climate.wiser_bad
      - climate.wiser_flur
      - climate.wiser_wohnzimmer
google_assistant:
  project_id: !secret gproject_id
  service_account: !secret google_service_accout_json_file
  report_state: false
  expose_by_default: false
  #  api_key: !secret google_assistantapikey_pwd
  exposed_domains:
    - light
    - switch
    - camera
    #    - input_boolean
    - scene
    - sensor
#    - climate
input_boolean:
  home_mode_party:
    name: Party Mode
    initial: off
binary_sensor:
  - platform: workday
    country: DE
    excludes: [sat, sun, holiday]
    province: BY
    add_holidays:
      - 2019-12-24
  - platform: template
    sensors:
      dark_outside:
        value_template: "{{ is_state('sun.sun', 'below_horizon') }}"
        friendly_name: "Dark Outside"
  - platform: bayesian
    prior: 0.5
    name: "Martin's Presence"
    probability_threshold: 0.9
    observations:
      - entity_id: "device_tracker.pixel_gps"
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: "state"
        to_state: "home"
      - entity_id: "device_tracker.pixel_wifi"
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: "state"
        to_state: "home"
      - entity_id: "device_tracker.pixel_ping"
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: "state"
        to_state: "home"
notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_pwd
    user_key: !secret pushover_user_pwd
  - name: android
    platform: nfandroidtv
    host: !secret host_androidtv
    position: top-right
    fontsize: medium
  - name: Google Assistant
    platform: rest
    resource: !secret google_assistant_webserver_bc
  - name: Google Assistant Command
    platform: rest
    resource: !secret google_assistant_webserver_cmd
recorder:
  purge_interval: 1
  purge_keep_days: 30
  db_url: !secret dburl
  exclude:
    entities:
      - automation.party_mode
      - automation.chill_mode
      - automation.lights_chill_mode
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
      - script
logbook:
  exclude:
    entities:
      - automation.party_mode
      - automation.chill_mode
      - automation.lights_chill_mode
      - script.party_mode_lights_on
      - script.pre_chill_mode
      - script.lights_mode_chill_off
      - script.lights_mode_chill_on
      - script.chill_mode_lights_on
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing
history:
  exclude:
    entities:
      - automation.party_mode
      - automation.chill_mode
      - automation.lights_chill_mode
      - script.party_mode_lights_on
      - script.pre_chill_mode
      - script.lights_mode_chill_off
      - script.lights_mode_chill_on
      - script.chill_mode_lights_on
    domains:
      - updater
      - camera
      - media_player
      - weather
      - sun
      - image_processing

coinbase:
  api_key: !secret coinbasekey_pwd
  api_secret: !secret coinbasesecret_pwd
  account_balance_currencies:
    - EUR
    - BTC
proximity:
  home:
    devices:
      - person.martin
    tolerance: 50
    unit_of_measurement: m
  home_away:
    devices:
      - person.martin
    unit_of_measurement: m
    tolerance: 50
device_tracker:
  - platform: composite
    name: "Google Pixel"
    time_as: device_or_local
    entity_id:
      - device_tracker.pixel_gps
      - device_tracker.pixel_wifi
      - device_tracker.pixel_ping
  - platform: composite
    name: "Google Nexus"
    time_as: device_or_local
    entity_id:
      - device_tracker.nexus_gps
      - device_tracker.nexus_wifi
  - platform: nmap_tracker
    hosts:
      - 10.10.10.104
      - 10.10.10.108
    home_interval: 10
camera:
  - platform: generic
    still_image_url: https://www.yr.no/place/Germany/Bavaria/Munich/meteogram.svg
    name: Weather
    content_type: "image/svg+xml"
  - platform: mjpeg
    mjpeg_url: !secret mjpeg_url
    name: Wohnzimmer
  - platform: local_file
    file_path: "/config/tmp/wohnzimmer_latest.jpg"
    name: Tensorflow Wohnzimmer
  #  - platform: local_file
  #    file_path: "/config/tmp/marienplatz_latest.jpg"
  #    name: Tensorflow Marienplatz
  #  - platform: local_file
  #    file_path: "/config/tmp/marienplatz_beck_latest.jpg"
  #    name: Tensorflow Marienplatz Beck
  #  - platform: local_file
  #    file_path: "/config/tmp/westin_grand_latest.jpg"
  #    name: Tensorflow Westin Grand
  #  - platform: local_file
  #    file_path: "/config/tmp/studentenstadt_latest.jpg"
  #    name: Tensorflow Studentenstadt
  #  - platform: local_file
  #    file_path: "/config/tmp/freimann_latest.jpg"
  #    name: Tensorflow Freimann
  #  - platform: local_file
  #    file_path: "/config/tmp/wiener_platz_latest.jpg"
  #    name: Tensorflow Wiener Platz
  - platform: mjpeg
    mjpeg_url: "https://app.muenchen.de/webcam/marienplatz//marienplatzgross000M.jpg"
    name: Marienplatz
  - platform: mjpeg
    mjpeg_url: "http://ftp.kaufhaus.ludwigbeck.de/webcam/webcam.jpg"
    name: Marienplatz Beck
  - platform: mjpeg
    mjpeg_url: "https://images-webcams.windy.com/10/1512053210/current/full/1512053210.jpg"
    name: Westin Grand
  - platform: mjpeg
    mjpeg_url: "https://www.foto-webcam.eu/webcam/freimann/current/1200.jpg"
    name: Freimann
  - platform: mjpeg
    mjpeg_url: "https://www.foto-webcam.eu/webcam/muenchen/current/1200.jpg"
    name: Studentenstadt
  - platform: mjpeg
    mjpeg_url: "http://hb-webcam.registrierung.net/biergarten.jpg"
    name: Wiener Platz
#  - platform: generic
#    name: Google Maps
#    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ state_attr('sensor.martin', 'current_latitude') }},{{ state_attr('sensor.martin', 'current_longitude') }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:Martin%7C{{ state_attr('sensor.martin', 'current_latitude') }},{{ state_attr('sensor.martin', 'current_longitude') }}&key='!secret google_assistantapikey_pwd'
#    limit_refetch_to_url_change: true
image_processing:
  - platform: tensorflow
    scan_interval: 10000
    source:
      - entity_id: camera.marienplatz
      - entity_id: camera.marienplatz_beck
      - entity_id: camera.westin_grand
      - entity_id: camera.studentenstadt
      - entity_id: camera.wiener_platz
      - entity_id: camera.freimann
    file_out:
      - "/config/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
    model:
      graph: /config/tensorflow/frozen_inference_graph.pb
  - platform: tensorflow
    source:
      - entity_id: camera.wohnzimmer
    file_out:
      - "/config/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
    #      - "/config/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: /config/tensorflow/frozen_inference_graph.pb
utility_meter:
  energy_consumed_hourly_whz_1:
    source: sensor.energy_consumtion_whz_1
    cycle: hourly
  energy_consumed_daily_whz_1:
    source: sensor.energy_consumtion_whz_1
    cycle: daily
  energy_consumed_weekly_whz_1:
    source: sensor.energy_consumtion_whz_1
    cycle: weekly
  energy_consumed_monthly_whz_1:
    source: sensor.energy_consumtion_whz_1
    cycle: monthly
gpodder:
  username: !secret gpodder_user
  password: !secret gpodder_password
  sensor:
    - enabled: true
      name: podcasts
      device: hassio
