# ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ ██╗   ██╗██████╗  █████╗ ████████╗██╗ ██████╗ ███╗   ██╗
#██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ ██║   ██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║
#██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗██║   ██║██████╔╝███████║   ██║   ██║██║   ██║██╔██╗ ██║
#██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║██║   ██║██╔══██╗██╔══██║   ██║   ██║██║   ██║██║╚██╗██║
#╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║
# ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
automation: !include automations.yaml
script: !include scripts.yaml
upnp: !include upnp.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
panel_iframe: !include panels.yaml
sensor: !include sensors.yaml
# homeassistant starts here most stuff is in integrations directory
homeassistant:
  packages: !include_dir_named integrations
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - !secret trusted_network_1
        - !secret trusted_network_2
        - !secret trusted_network_3
        - !secret trusted_network_4
  auth_mfa_modules:
    - type: totp
      name: Authy
    - type: notify
      message: "Hey, to get into my clubhouse, you need to say {}"
  name: Home
  time_zone: Europe/Berlin
  unit_system: metric
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_ela
  whitelist_external_dirs:
    - /config/tmp
    - /config
    - /config/integrations
    - /config/google-assistant-entities


