#  - platform: attributes
#    friendly_name: "Batteries"
#    attribute: battery_level
#    unit_of_measurement: "%"
#    entities:
#      - sensor.battery_level_pixel
#  - platform: rest
#    resource: http://api.muc.ccc.de/spaceapi.json
#    name: muccc
#    value_template: >
#      {% for x in value_json %}
#        '{{ loop.index }}. {{ x.title }}'
#      {% endfor %}
#  - platform: steam_online
#    api_key: !secret steam_apikey
#    accounts:
#      - !secret steam_account
- platform: version
  image: qemux86-64
  source: local
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: throughput_network_in
      arg: enp0s31f6
    - type: throughput_network_out
      arg: enp0s31f6
    - type: network_in
      arg: enp0s31f6
    - type: network_out
      arg: enp0s31f6
- platform: integration
  source: sensor.sonoff_pow_r2_whz_power
  name: energy_consumtion_whz_1
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.sonoff_pow_r2_tv_power
  name: energy_consumtion_whz_2
  unit_prefix: k
  round: 2
- platform: github
  access_token: !secret github_access_token
  repositories:
    - path: "home-assistant/home-assistant"
    - path: "phixion/sopel-modules"
    - path: "phixion/home-assistantconfig"
#  - platform: command_line
#    name: installed version
#    command: "cat /config/.HA_VERSION"
#- platform: command_line
#  name: pending OS update(s)
#  unit_of_measurement: pending update(s)
#  command: "cat /config/ubuntu_updates.log"
- platform: dnsip
  hostname: !secret home_host
  name: !secret home_host
  resolver: 1.1.1.1
- platform: reddit
  username: !secret reddit_username
  password: !secret reddit_password
  client_id: !secret reddit_client_id
  client_secret: !secret reddit_client_secret
  subreddits:
    - gamedeals
  sort_by: new
- platform: alpha_vantage
  api_key: !secret alphavantage_apipwd
  foreign_exchange:
    - from: BTC
      to: EUR
      name: BTC Exchange rate
    - from: XLM
      to: EUR
      name: XLM Exchange rate
- platform: feedparser
  name: !secret feed_1_name
  feed_url: !secret feed_1_url
  inclusions:
    - title
    - link
    - pubDate
  exclusions:
    - image
- platform: feedparser
  name: rss free steam keys
  feed_url: "https://www.reddit.com/r/GameDeals/search.rss?q=steam+free&sort=new&restrict_sr=on&t=all.rss"
  inclusions:
    - title
    - link
    - pubDate
  exclusions:
    - image
- platform: feedparser
  name: rss haveibeenpwnd
  feed_url: "http://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches"
  inclusions:
    - title
    - link
    - pubDate
  exclusions:
    - image
- platform: feedparser
  name: rss coindesk
  feed_url: "https://www.coindesk.com/feed"
  inclusions:
    - title
    - link
    - pubDate
  exclusions:
    - image
- platform: places
  name: Martin
  devicetracker_id: device_tracker.google_pixel
  options: zone,place,street_number,street,city,state,postal_code
  map_provider: google
  map_zoom: 19
  home_zone: zone.home
  api_key: !secret email_phixion
- platform: rest
  resource: https://api.myip.com
  name: External IP
  value_template: "{{ value_json.ip }}"
- platform: authenticated
- platform: uptime
  unit_of_measurement: days
- platform: mvglive
  nextdeparture:
    - station: !secret station_mvg_tram
      destinations: !secret destination_tram
      name: Tram
      lines: !secret line_tram
      products: ["Tram", "Nachteule"]
      number: 3
    - station: !secret station_mvg_bus
      destinations: !secret destination_bus
      name: Bus
      lines: !secret line_bus
      products: ["Bus"]
      number: 3
    - station: !secret station_mvg_u
      name: U-Bahn
      directions: ["2"]
      products: ["U-Bahn"]
      number: 3
- platform: unifigateway
  host: !secret unifigw_host
  port: !secret unifigw_port
  username: !secret unifigw_user
  password: !secret unifigw_pwd
  monitored_conditions:
    - www
    - wlan
    - alerts
    - firmware
  site_id: !secret unifigw_site
  verify_ssl: false
- platform: template
  sensors:
    climate_wohnung_temp:
      friendly_name: "Wohnung"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.alle_thermostate.attributes.current_temperature }}"
    climate_flur_temp:
      friendly_name: "Flur"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.wiser_flur.attributes.current_temperature }}"
    climate_bad_temp:
      friendly_name: "Bad"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.wiser_bad.attributes.current_temperature }}"
    climate_wohnzimmer_temp:
      friendly_name: "Wohnzimmer"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.wiser_wohnzimmer.attributes.current_temperature }}"
    climate_wohnung_target_temp:
      friendly_name: "Target Temp Wohnung"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.alle_thermostate.attributes.temperature }}"
    climate_flur_target_temp:
      friendly_name: "Target Temp Flur"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.wiser_flur.attributes.temperature }}"
    climate_bad_target_temp:
      friendly_name: "Target Temp Bad"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.wiser_bad.attributes.temperature }}"
    climate_wohnzimmer_target_temp:
      friendly_name: "Target Temp Wohnzimmer"
      unit_of_measurement: "°C"
      value_template: "{{ states.climate.wiser_wohnzimmer.attributes.temperature }}"
    climate_wohnzimmer_window:
      friendly_name: "Fenster Wohnzimmer"
      value_template: "{{ states.climate.wiser_wohnzimmer.attributes.window_state }}"
    climate_bad_window:
      friendly_name: "Fenster Bad"
      value_template: "{{ states.climate.wiser_bad.attributes.window_state }}"
    climate_flur_window:
      friendly_name: "Fenster Flur"
      value_template: "{{ states.climate.wiser_flur.attributes.window_state }}"
    climate_wohnzimmer_battery:
      friendly_name: "Thermostat Wohnzimmer Battery"
      value_template: "{{ state_attr('sensor.wiser_itrv_wohnzimmer','battery_level') }}"
      icon_template: mdi:battery-charging-40
      device_class: battery
    climate_bad_battery:
      friendly_name: "Thermostat Bad Battery"
      value_template: "{{ state_attr('sensor.wiser_itrv_bad','battery_level') }}"
      device_class: battery
      icon_template: mdi:battery-charging-40
    climate_flur_battery:
      friendly_name: "Thermostat Flur Battery"
      value_template: "{{ state_attr('sensor.wiser_itrv_flur','battery_level') }}"
      device_class: battery
      icon_template: mdi:battery-charging-40
    climate_roomstat_battery:
      friendly_name: "Raum Thermostat Battery"
      value_template: "{{ state_attr('sensor.sensor.wiser_roomstat_wohnzimmer','battery_level') }}"
      device_class: battery
      icon_template: mdi:battery-charging-40
    climate_wohnzimmer_battery_voltage:
      friendly_name: "Thermostat Wohnzimmer Voltage"
      unit_of_measurement: "V"
      value_template: "{{ state_attr('sensor.wiser_itrv_wohnzimmer','battery_voltage') }}"
      icon_template: mdi:flash
    climate_bad_battery_voltage:
      friendly_name: "Thermostat Bad Voltage"
      unit_of_measurement: "V"
      value_template: "{{ state_attr('sensor.wiser_itrv_bad','battery_voltage') }}"
      icon_template: mdi:flash
    climate_flur_battery_voltage:
      friendly_name: "Thermostat Flur Voltage"
      unit_of_measurement: "V"
      value_template: "{{ state_attr('sensor.wiser_itrv_flur','battery_voltage') }}"
      icon_template: mdi:flash
    climate_roomstat_battery_voltage:
      friendly_name: "Raum Thermostat Voltage"
      unit_of_measurement: "V"
      value_template: "{{ state_attr('sensor.sensor.wiser_roomstat_wohnzimmer','battery_voltage') }}"
      icon_template: mdi:flash
    climate_bad_preset:
      friendly_name: "Bad Modus"
      value_template: "{{ states.climate.wiser_bad.attributes.preset_mode }}"
    climate_wohnzimmer_preset:
      friendly_name: "Wohnzimmer Modus"
      value_template: "{{ states.climate.wiser_wohnzimmer.attributes.preset_mode }}"
    climate_flur_preset:
      friendly_name: "Flur Modus"
      value_template: "{{ states.climate.wiser_flur.attributes.preset_mode }}"
    unifi_speedtest_rx:
      entity_id: sensor.unifi_gateway_www
      friendly_name: "Download"
      unit_of_measurement: MB/s
      value_template: "{{ state_attr('sensor.unifi_gateway_www','xput_down') }}"
    unifi_speedtest_tx:
      entity_id: sensor.unifi_gateway_www
      friendly_name: "Upload"
      unit_of_measurement: MB/s
      value_template: "{{ state_attr('sensor.unifi_gateway_www','xput_up') }}"
    unifi_speedtest_ping:
      entity_id: sensor.unifi_gateway_www
      friendly_name: "Ping"
      unit_of_measurement: ms
      value_template: "{{ state_attr('sensor.unifi_gateway_www','speedtest_ping') }}"
    unifi_wlan_user:
      entity_id: sensor.unifi_gateway_wlan
      friendly_name: "WLAN User"
      unit_of_measurement: devices
      value_template: "{{ state_attr('sensor.unifi_gateway_wlan','num_user') }}"
    unifi_wlan_guest:
      entity_id: sensor.unifi_gateway_wlan
      friendly_name: "WLAN Guests"
      unit_of_measurement: devices
      value_template: "{{ state_attr('sensor.unifi_gateway_wlan','num_guests') }}"
    unifi_wlan_iot:
      entity_id: sensor.unifi_gateway_wlan
      friendly_name: "WLAN IoT"
      unit_of_measurement: devices
      value_template: "{{ state_attr('unifi_gateway_wlan','num_iot') }}"
    sun_sunset:
      entity_id: sun.sun
      friendly_name: "Sonnenuntergang"
      value_template: "{{ state_attr('sun.sun','next_dusk') }}"
    sun_sunrise:
      entity_id: sun.sun
      friendly_name: "Sonnenaufgang"
      value_template: "{{ state_attr('sun.sun','next_dawn') }}"
    battery_level_google_pixel:
      entity_id: device_tracker.google_pixel
      friendly_name: Batterylevel Pixel
      unit_of_measurement: "%"
      value_template: >-
        {%- if state_attr('device_tracker.google_pixel', 'battery') %}
            {{ state_attr('device_tracker.google_pixel', 'battery')|round }}
        {% else %}
            {{ states('sensor.battery.google_pixel') }}
        {%- endif %}
      device_class: battery
    battery_level_google_nexus:
      entity_id: device_tracker.google_nexus
      friendly_name: Batterylevel Nexus
      unit_of_measurement: "%"
      value_template: >-
        {%- if state_attr('device_tracker.google_nexus', 'battery') %}
            {{ state_attr('device_tracker.google_nexus', 'battery')|round }}
        {% else %}
            {{ states('device_tracker.google_nexus') }}
        {%- endif %}
      device_class: battery
    proximity_dir_of_travel:
      entity_id: proximity.home
      friendly_name: "Direction of travel"
      value_template: "{{ state_attr('proximity.home','dir_of_travel') }}"
    energy_consumtion_combined:
      value_template: "{{ ((states.sensor.energy_consumtion_whz_1.state | float) + (states.sensor.energy_consumtion_whz_2.state | float)) | round(2) }}"
      friendly_name: "Energy consumtion combined"
      unit_of_measurement: "kwh"
    energy_combined_current:
      value_template: "{{ ((states.sensor.sonoff_pow_r2_tv_current.state | float) + (states.sensor.sonoff_pow_r2_whz_current.state | float)) | round(3) }}"
      friendly_name: "Energy combined current"
      unit_of_measurement: "A"
    energy_combined_power:
      value_template: "{{ ((states.sensor.sonoff_pow_r2_tv_power.state | float) + (states.sensor.sonoff_pow_r2_whz_power.state | float)) | round(2) }}"
      friendly_name: "Energy combined power"
      unit_of_measurement: "W"
    energy_combined_voltage:
      value_template: "{{ (((states.sensor.sonoff_pow_r2_tv_voltage.state | float) + (states.sensor.sonoff_pow_r2_whz_voltage.state | float)) / 2) | round(2) }}"
      friendly_name: "Energy combined voltage"
      unit_of_measurement: "V"
    coinbase_vault_in_euro:
      entity_id: sensor.coinbase_btc_vault
      friendly_name: "Coinbase BTC Vault (EUR)"
      unit_of_measurement: EUR
      value_template: "{{ ((states.sensor.coinbase_btc_vault.state | float) * (states.sensor.btc_exchange_rate.state | float)) | round(2)}}"
    coinbase_wallet_in_euro:
      entity_id: sensor.coinbase_btc_wallet
      friendly_name: "Coinbase BTC Wallet (EUR)"
      unit_of_measurement: EUR
      value_template: "{{ ((states.sensor.coinbase_btc_wallet.state | float) * (states.sensor.btc_exchange_rate.state | float)) | round(2)}}"
    coinbase_euro:
      value_template: "{{ ((states.sensor.coinbase_vault_in_euro.state | float) + (states.sensor.coinbase_wallet_in_euro.state | float) + (states.sensor.coinbase_eur_wallet.state | float)) | round(2)}}"
      friendly_name: "Coinbase Deposit (EUR)"
      unit_of_measurement: "EUR"
- platform: qnap
  host: !secret qnap_host
  username: !secret qnap_usr
  password: !secret qnap_pwd
  ssl: true
  verify_ssl: false
  port: 443
  monitored_conditions:
    - status
    - cpu_usage
    - memory_percent_used
    - network_tx
    - volume_percentage_used
- platform: scrape
  name: HA upstream
  resource: https://pypi.org/project/homeassistant/#history
  select: 'a[href^="/project/homeassistant/0"]'
- platform: scrape
  name: wtfisxur
  resource: https://wherethefuckisxur.com/
  select: "h1.page-title"
- platform: darksky
  api_key: !secret weatherdarkskyapi_pwd
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
- platform: google_travel_time
  name: Morning Commute (Trains)
  api_key: !secret google_assistantapikey_pwd
  origin: device_tracker.google_pixel
  destination: zone.work
  options:
    mode: transit
    transit_mode: train
    transit_routing_preference: fewer_transfers
- platform: google_travel_time
  name: Morning Commute (Bike)
  api_key: !secret google_assistantapikey_pwd
  origin: device_tracker.google_pixel
  destination: zone.work
  options:
    mode: bicycling
- platform: google_travel_time
  name: Commute Home
  api_key: !secret google_assistantapikey_pwd
  origin: device_tracker.google_pixel
  destination: zone.home
- platform: attributes
  friendly_name: "Batteries"
  attribute: battery_level
  unit_of_measurement: "%"
  entities:
    - device_tracker.pixel_gps
    - device_tracker.nexus_gps
