custom_header:
  compact_mode: true
  hide_help: true
resources:
  - type: module
    url: /community_plugin/weather-card/weather-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /community_plugin/lovelace-layout-card/layout-card.js
  - type: js
    url: /community_plugin/rgb-light-card/card.js
  - type: js
    url: /local/lovelace/card-modder.js?v=785dd6
  - type: js
    url: /community_plugin/light-entity-card/light-entity-card.js
  - type: module
    url: /community_plugin/button-toolbar/button-toolbar.js
  - type: js
    url: /community_plugin/bar-card/bar-card.js
  - type: js
    url: /local/list-card.js?v=0
  - type: module
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: module
    url: /community_plugin/lovelace-card-mod/card-mod.js
  - type: module
    url: /community_plugin/search-card/search-card.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: js
    url: /community_plugin/lovelace-github-entity-row/github-entity-row.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
  - type: module
    url: /community_plugin/simple-thermostat/simple-thermostat.js
title: ''
views:
  !include_dir_merge_list views/