- alias: Notification something new in HACS
  id: "20"
  trigger:
    - platform: event
      event_type: hacs/repository
      event_data:
        action: registration
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.repository is defined }}"
  action:
    - service: persistent_notification.create
      data_template:
        title: New repository in HACS
        message:
          "{% set repo = trigger.event.data.repository %} {% set id = trigger.event.data.repository_id\
          \ %}\n [{{ repo }}](/hacs/repository/{{ id }})\n was just added to HACS."