- alias: Notification Xur
  id: "19"
  trigger:
    - platform: state
      entity_id: sensor.wtfisxur
  action:
    - service: notify.telegram
      data_template:
        title: Xur changed location
        message: "{{states('sensor.wtfisxur')}}"
- alias: Update Xur Sensor
  id: "17"
  trigger:
    - platform: time_pattern
      minutes: /120
  condition:
    condition: time
    after: "19:00:00"
    weekday:
      - fri
      - sat
      - sun
      - mon
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.wtfisxur