#SmartHome IR+WiFI GPIO IR pin configured to be a ws2814 addressable data pin
substitutions:
  devicename: ledstripwhz2
  friendly_name: "LED Strip Wohnzimmer 2"
  update_interval: 10min
  frequency_rgb: 1000 Hz
  frequency_w: 1000 Hz
esphome:
  esp8266_restore_from_flash: true
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
web_server: !include shared/webserver.yaml
globals: !include shared/globals.yaml
wifi: !include shared/wifi.yaml
light: !include shared/rgbw.yaml
output: !include shared/rgbwoutput.yaml
text_sensor: !include shared/textsensors.yaml
sensor: !include shared/sensors.yaml
time: !include shared/time.yaml
api:
  password: !secret esphome_api_pwd
ota:
  safe_mode: true
  password: !secret esphome_ota_pwd
captive_portal:
logger:
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: ${devicename}_binbutton
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: ${devicename}_button
    internal: true
switch:
  - platform: restart
    name: ${friendly_name} Restart
  - platform: template
    name: ${friendly_name} Schalter
    optimistic: true
    internal: true
    restore_state: true
    id: ${devicename}_button
    turn_on_action:
      - light.turn_on: ${devicename}_rgb
        brightness: 100%
    turn_off_action:
      - light.turn_off: ${devicename}_rgb
#remote_receiver:
#  pin:
#    number: GPIO4
#    inverted: true
#  dump: all