#Lumninea LAC ZX2843-675 RGBW with W disbled
#Plattenschrank klein
substitutions:
  devicename: ledstripwhz3
  friendly_name: "LED Strip Wohnzimmer 3"
  update_interval: 10min
  frequency_rgb: 100 Hz
esphome:
  esp8266_restore_from_flash: true
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
web_server: !include shared/webserver.yaml
globals: !include shared/globals.yaml
light: !include shared/rgb.yaml
output: !include shared/rgboutput.yaml
text_sensor: !include shared/textsensors.yaml
sensor: !include shared/sensors.yaml
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
captive_portal:
logger:
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    internal: true
    id: ${devicename}_binbutton
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: ${devicename}_button
  - platform: status
    name: ${friendly_name} Status
switch:
  - platform: restart
    name: ${friendly_name} Restart
  - platform: template
    name: ${friendly_name} Schalter
    optimistic: true
    internal: true
    restore_state: true
    id: ${devicename}_button
    turn_on_action:
      - light.turn_on: ${devicename}_rgb
    turn_off_action:
      - light.turn_off: ${devicename}_rgb

