#SmartHome led controller
substitutions:
  devicename: ledstripwhz2
  friendly_name: LED Strip 2
  room: Wohnzimmer
  update_interval_short: 2s
  update_interval_long: 10min
  frequency_rgb: 1000 Hz
  frequency_w: 1000 Hz
esphome:
  esp8266_restore_from_flash: true
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
web_server: !include shared/webserver.yaml
globals: !include shared/globals.yaml
light: !include shared/rgb.yaml
output: !include shared/rgboutput.yaml
text_sensor: !include shared/textsensors.yaml
binary_sensor: !include shared/binarysensors.yaml
sensor: !include shared/sensors.yaml
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
captive_portal:
logger:
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
  - platform: template
    name: ${friendly_name} (${room}) Schalter
    optimistic: true
    internal: true
    restore_state: true
    id: ${devicename}_button
    turn_on_action:
      - light.turn_on: ${devicename}_rgb
    turn_off_action:
      - light.turn_off: ${devicename}_rgb
#remote_receiver:
#  pin:
#    number: GPIO4
#    inverted: true
#  dump: all
