substitutions:
  devicename: nodemcu3
  friendly_name: Nodemcu 3
  update_interval: 10min
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
web_server: !include shared/webserver.yaml
captive_portal:
logger:
switch:
  - platform: restart
    name: ${friendly_name} Restart
i2c:
  sda: D2
  scl: D1
  scan: True
sensor:
  - platform: bh1750
    name: "${friendly_name} Lichtsensor"
    address: 0x23
    resolution: 0.5
    update_interval: 60s
    unit_of_measurement: lx
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: ${update_interval}
    unit_of_measurement: dB
    icon: mdi:wifi
    force_update: true
  - platform: uptime
    force_update: true
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
    icon: mdi:alarm
binary_sensor:
  - platform: status
    device_class: connectivity
    name: ${friendly_name} Status
