substitutions:
  devicename: nodemcu2
  friendly_name: Nodemcu 2
  update_interval_short: 2s
  update_interval_long: 10min
  room: TV
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
web_server: !include shared/webserver.yaml
captive_portal:
logger:
i2c:
  sda: D6
  scl: D7
  scan: True
apds9960:
  address: 0x39
  update_interval: 60s
sun:
  latitude: !secret home_lat
  longitude: !secret home_lon
sensor:
  - platform: sun
    name: ${friendly_name} (${room}) Sonne Elevation
    type: elevation
    update_interval: 60s
  - platform: sun
    name: ${friendly_name} (${room}) Sonne Azimuth
    type: azimuth
    update_interval: 60s
  - platform: bh1750
    name: ${friendly_name} (${room}) Lichtsensor
    address: 0x23
    unit_of_measurement: lx
  - platform: wifi_signal
    name: ${friendly_name} (${room}) WiFi Signal
    update_interval: ${update_interval_long}
    unit_of_measurement: dB
    icon: mdi:wifi
    force_update: true
  - platform: apds9960
    type: CLEAR
    name: ${friendly_name} (${room}) CLEAR
  - platform: apds9960
    type: RED
    name: ${friendly_name} (${room}) RED
  - platform: apds9960
    type: GREEN
    name: ${friendly_name} (${room}) GREEN
  - platform: apds9960
    type: BLUE
    name: ${friendly_name} (${room}) BLUE
  - platform: apds9960
    type: PROXIMITY
    name: ${friendly_name} (${room}) PROXIMITY
  - platform: bme280
    temperature:
      name: ${friendly_name} (${room}) Temperatur
      id: bme280_temperature
      unit_of_measurement: "°C"
      icon: "mdi:thermometer-lines"
    pressure:
      name: ${friendly_name} (${room}) Absoluter Luftdruck
      id: bme280_pressure
      unit_of_measurement: hPa
      icon: mdi:gauge
    humidity:
      name: ${friendly_name} (${room}) Relative Luftfeuchtigkeit
      id: bme280_humidity
      unit_of_measurement: "%"
      icon: "mdi:water-percent"
    address: 0x77
    update_interval: 15s
  - platform: template
    name: ${friendly_name} (${room}) Höhe NHN
    unit_of_measurement: m
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(bme280_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(bme280_pressure).state), 0.190234) - 1); // in meter
    update_interval: 15s
  - platform: template
    name: ${friendly_name} (${room}) Absolute Luftfeuchtigkeit
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(bme280_temperature).state) /
        (id(bme280_temperature).state + 243.5)) * id(bme280_humidity).state * mw) /
        ((273.15 + id(bme280_temperature).state) * r); // in grams/m^3
    unit_of_measurement: 'g/m³'
    accuracy_decimals: 2
    update_interval: 15s
  - platform: adc
    pin: A0
    update_interval: ${update_interval}
    name: ${friendly_name} (${room}) Audio Meter
    filters:
      - multiply: 3.3
    unit_of_measurement: dB
binary_sensor:
  - platform: gpio
    pin: D3
    device_class: sound
    name: ${friendly_name} (${room}) Noise Sensor
    filters:
      - delayed_off: 120s
    on_state:
      then:
        - script.execute: beep
  - platform: apds9960
    direction: UP
    name: ${friendly_name} (${room}) UP
  - platform: apds9960
    direction: DOWN
    name: ${friendly_name} (${room}) DOWN
  - platform: apds9960
    direction: LEFT
    name: ${friendly_name} (${room}) LEFT
  - platform: apds9960
    direction: RIGHT
    name: ${friendly_name} (${room}) RIGHT
  - platform: status
    device_class: connectivity
    name: ${friendly_name} (${room}) Status
output:
  - platform: esp8266_pwm
    pin: D5
    id: buzzer
script:
  - id: beep
    then:
      - output.esp8266_pwm.set_frequency:
          id: buzzer
          frequency: 900
      - output.set_level:
          id: buzzer
          level: 30%
      - delay: 90ms
      - output.turn_off: buzzer
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
text_sensor:
  - platform: sun
    name: ${friendly_name} (${room}) Sonnenaufgang
    type: sunrise
  - platform: sun
    name: ${friendly_name} (${room}) Sonnenuntergang
    type: sunset
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
      icon: mdi:wifi
