substitutions:
  devicename: nodemcu6
  friendly_name: Nodemcu 6
  update_interval: 60s
  room: Wohnzimmer
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
text_sensor: !include shared/textsensors.yaml
web_server: !include shared/webserver.yaml
logger:
sensor:
  - platform: adc
    pin: A0
    update_interval: ${update_interval}
    name: ${friendly_name} (${room}) Air Sensor
    icon: mdi:air-filter
    unit_of_measurement: ppm
    filters:
      lambda: |-
        return (x * 1023/5);
  - platform: wifi_signal
    name: ${friendly_name} (${room}) WiFi Signal
    update_interval: ${update_interval}
    unit_of_measurement: dB
    icon: mdi:wifi
    force_update: true
switch:
  - platform: restart
    name: ${friendly_name} (${room}) Restart
