substitutions:
  devicename: nodemcu6
  friendly_name: Nodemcu 6
  update_interval: 60s
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
text_sensor: !include shared/textsensors.yaml
web_server: !include shared/webserver.yaml
captive_portal:
logger: 
i2c:
  sda: D2
  scl: D1
  scan: True
sensor:
  - platform: adc
    pin: A0
    update_interval: ${update_interval}
    name: ${friendly_name} (${room}) Audio Meter
    unit_of_measurement: dB
  - platform: wifi_signal
    name: ${friendly_name} (${room}) WiFi Signal
    update_interval: ${update_interval}
    unit_of_measurement: dB
    icon: mdi:wifi
    force_update: true
  - platform: uptime
    force_update: true
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
    icon: mdi:alarm
binary_sensor:
  - platform: gpio
    pin: D4
    name: ${friendly_name} (${room}) Bluetooth Presence
    device_class: presence
    filters:
      - delayed_off: 120s
    on_state:
      then:
        - script.execute: beep
  - platform: status
    device_class: connectivity
    name: ${friendly_name} Status
output:
  - platform: esp8266_pwm
    pin: D5
    id: buzzer
script:
  - id: beep
    then:
      - output.esp8266_pwm.set_frequency:
          id: buzzer
          frequency: 900
      - output.set_level:
          id: buzzer
          level: 30%
      - delay: 90ms
      - output.turn_off: buzzer
switch:
  - platform: restart
    name: ${friendly_name} Restart
remote_receiver:
  pin: D6
  dump: all