substitutions:
  devicename: nodemcu5
  friendly_name: Nodemcu 5 (Bad)
  update_interval: 60s
esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s
  board_flash_mode: dout
time: !include shared/time.yaml
wifi: !include shared/wifi.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
web_server: !include shared/webserver.yaml
captive_portal:
logger:
#esp32_ble_tracker:
#esp32_ble_beacon:
#  type: iBeacon
#  uuid: 8bbe8db6-3b5e-bac3-e6f7-28433bdd3065
sensor:
#  - platform: ble_rssi
#    mac_address: B8:E8:56:00:EA:3F
#    name: "BLE Macbook Air RSSI"
#  - platform: ble_rssi
#    mac_address: 40:4E:36:56:7E:2F
#    name: "BLE Google Pixel RSSI"
#  - platform: ble_rssi
#    mac_address: b4:ce:f6:08:f0:71
#    name: "BLE Google Nexus RSSI"
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: ${update_interval}
    unit_of_measurement: dB
    icon: mdi:wifi
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
    icon: mdi:alarm
binary_sensor:
  - platform: gpio
    pin: GPIO13
    id: ${devicename}_motion
    name: ${friendly_name} Motion Sensor
    device_class: motion
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: switch.schalter_bad_relay
  - platform: template
    id: ${devicename}_templ
    internal: true
    lambda: 'return id(${devicename}_motion).state;'
    filters:
      - delayed_off: 2min
    on_release:
      - homeassistant.service:
          service: switch.turn_off
          data:
            entity_id: switch.schalter_bad_relay
#  - platform: ble_presence
#    mac_address: B8:E8:56:00:EA:3F
#    name: "BLE Macbook Air Presence"
#  - platform: ble_presence
#    mac_address: 40:4E:36:56:7E:2F
#    name: "BLE Google Pixel Presence"
#    device_class: presence
#  - platform: ble_presence
#    mac_address: ac:37:43:e0:ea:d8
#    name: "BLE Google Nexus Presence"
#    device_class: presence
  - platform: status
    device_class: connectivity
    name: ${friendly_name} Status
switch:
  - platform: restart
    name: ${friendly_name} Restart
