---
name: Home Assistant Installed

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."
  home_assistant_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@master
      - name: Install dependencies
        run: sed 's/#.*//' $(pwd)/doc/travis/ubuntu_deps.lst | sudo apt-get install -y -o Dpkg::Options::=--force-confnew
      - name: rename yamls
        run: rename -v 's/travis_//' $(pwd)/doc/travis/*.{yaml,json}
      - name: link critical yamls
        run: ln -s $(pwd)/doc/travis/*.{yaml,json} .
      - name: fix path
        run: sed -i "s@/config/tmp@$(pwd)/tmp@" configuration.yaml
      - name: create tmp/
        run: mkdir $(pwd)/tmp
      - name: create gmaps cookie
        run: echo "# Netscape HTTP Cookie File\n0 0\n0 0\n0 0" > $(pwd)/.google_maps_location_sharing.cookies.joedoe_gmail_com
      - name: Home Assistant Check Latest
        uses: "docker://homeassistant/home-assistant:0.111.3"
        with:
          args: python -m homeassistant --config . --script check_config --info all
