---
name: Home Assistant Latest

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2
      - name: Super Lint
        uses: github/super-linter@v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: true
          VALIDATE_MD: true
          VALIDATE_SHELL: true
          DISABLE_ERRORS: true
  home_assistant_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@master
      - name: Install dependencies
        run: sudo apt-get -qq update && sed 's/#.*//' $(pwd)/.doc/CI/ubuntu_deps.lst | xargs sudo apt-get install -y -o Dpkg::Options::=--force-confnew
      - name: Copy stub files into configuration folder
        run: cp -R ./.doc/CI/* ./config
      - name: create gmaps cookie
        run: echo "# Netscape HTTP Cookie File\n0 0\n0 0\n0 0" > $(pwd)/.google_maps_location_sharing.cookies.joedoe_gmail_com
      - name: Home Assistant Check Latest
        uses: "docker://homeassistant/home-assistant:latest"
        with:
          args: python -m homeassistant --config . --script check_config --info all --secrets
